user_valid:
  name_length: 50
  email_length: 255
  email_syntax: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  password_length: 4
  avatar_size: 1
users:
  records: 5
default_params:
  href: "#"
  avatar: "default_avatar.jpg"
alive_time:
  reset_password: 2

number_answer: 4
number_page: 5
